package project

//Constants used client and server-side to for submission data.
const (
	ID           = "_id"
	PROJECT_ID   = "projectid"
	PROJECT      = "project"
	USER         = "user"
	TIME         = "time"
	MODE         = "mode"
	TYPE         = "type"
	SRC          = "src"
	EXEC         = "exec"
	CHANGE       = "change"
	ARCHIVE      = "archive"
	TEST         = "test"
	FILE_MODE    = "file_remote"
	TEST_MODE    = "archive_test"
	ARCHIVE_MODE = "archive_remote"
	FTYPE        = "ftype"
	NAME         = "name"
	PKG          = "package"
	NUM          = "num"
	MOD          = "mod"
	LANG         = "lang"
	SUBID        = "subid"
	INFO         = "info"
	DATA         = "data"
	RESULTS      = "results"
	JSRC         = ".java"
	JCOMP        = ".class"
	ZIP          = "zip"
	BIN_DIR      = "bin"
	SRC_DIR      = "src"
	JAVA         = "java"
	CLASS        = "class"
	EMPTY        = "empty"
	HTML         = "html"
	FILEID       = "fileid"
	SKELETON     = "skeleton"
)
