package project

//Constants used client and server-side to for submission data.
const (
	ID           = "_id"
	PROJECT_ID   = "projectid"
	PROJECT      = "project"
	USER         = "user"
	TIME         = "time"
	MODE         = "mode"
	TYPE         = "type"
	SRC          = "src"
	LAUNCH       = "launch"
	ARCHIVE      = "archive"
	TEST         = "test"
	FILE_MODE    = "file_remote"
	ARCHIVE_MODE = "archive_remote"
	NAME         = "name"
	PKG          = "package"
	LANG         = "lang"
	SUBID        = "subid"
	INFO         = "info"
	DATA         = "data"
	RESULTS      = "results"
	JSRC         = ".java"
	BIN_DIR      = "bin"
	SRC_DIR      = "src"
	HTML         = "html"
	FILEID       = "fileid"
	SKELETON     = "skeleton"
)
