package submission

//Constants used client and server-side to for submission data.
const (
	ID           = "_id"
	PROJECT      = "project"
	USER         = "user"
	TIME         = "time"
	MODE         = "mode"
	TYPE         = "type"
	SRC          = "src"
	EXEC         = "exec"
	CHANGE       = "change"
	ARCHIVE      = "archive"
	TEST         = "test"
	FILE_MODE    = "file_remote"
	TEST_MODE    = "archive_test"
	ARCHIVE_MODE = "archive_remote"
	FTYPE        = "ftype"
	NAME         = "name"
	PKG          = "pkg"
	NUM          = "num"
	MOD          = "mod"
	LANG         = "lang"
	SUBID        = "subid"
	INFO         = "info"
	DATA         = "data"
	RES          = "results"
	JSRC         = ".java"
	JCOMP        = ".class"
	BIN_DIR      = "bin"
	SRC_DIR      = "src"
	TESTS = "tests"
	NAMES = "names"
)